### ISSUE TITLE
Issue with Dataform Run

### ISSUE THREAD

**Issue by MonooPrasadSJ** [dataform-co/dataform-tracking#333]
This error showed up on run schedule 
![image](https://user-images.githubusercontent.com/103463754/206955718-8c85141c-6141-469b-806c-6db4d03d33f6.png)
https://app.dataform.co/#/5081020597534720/run/650834519660473

Can we understand what has caused this error and what we can do resolve this situation?

**Comment by G2H** [comment]
Hi - this issue can happen infrequently in legacy Dataform due to issues that are fixed in the GCP version. If this happens regularly, this could be due to your project being unusually large. If that's the case, the main solutions are to delete dead code or split the project into several. We're in the process of preparing guides for both. In the meantime, we can assist you in evaluating these options. Feel free to contact us at dataform-preview@google.com.
